name: "identity"
backend: "python"
max_batch_size: 8

input [
  {
    name: "INPUT"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

output [
  {
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

dynamic_batching {
  preferred_batch_size: [ 2, 4, 8 ]
  max_queue_delay_microseconds: 1000
}
