apiVersion: batch/v1
kind: Job
metadata:
  name: dns-load
  labels:
    experiment: coredns
spec:
  template:
    metadata:
      labels:
        experiment: coredns
    spec:
      restartPolicy: Never
      containers:
        - name: dnsutils
          image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
          command:
            - /bin/sh
            - -c
            - |
              for i in $(seq 1 500); do
                nslookup kubernetes.default.svc.cluster.local >/dev/null || exit 1
              done
              echo "completed DNS lookups"
  backoffLimit: 0
